/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './../routes/__root'
import { Route as LayoutImport } from './../routes/_layout'
import { Route as LayoutIndexImport } from './../routes/_layout/index'
import { Route as LayoutCollection2Import } from './../routes/_layout/collection-2'
import { Route as LayoutCollection1Import } from './../routes/_layout/collection-1'

// Create/Update Routes

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const LayoutIndexRoute = LayoutIndexImport.update({
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutCollection2Route = LayoutCollection2Import.update({
  path: '/collection-2',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutCollection1Route = LayoutCollection1Import.update({
  path: '/collection-1',
  getParentRoute: () => LayoutRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/_layout/collection-1': {
      id: '/_layout/collection-1'
      path: '/collection-1'
      fullPath: '/collection-1'
      preLoaderRoute: typeof LayoutCollection1Import
      parentRoute: typeof LayoutImport
    }
    '/_layout/collection-2': {
      id: '/_layout/collection-2'
      path: '/collection-2'
      fullPath: '/collection-2'
      preLoaderRoute: typeof LayoutCollection2Import
      parentRoute: typeof LayoutImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexImport
      parentRoute: typeof LayoutImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  LayoutRoute: LayoutRoute.addChildren({
    LayoutCollection1Route,
    LayoutCollection2Route,
    LayoutIndexRoute,
  }),
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_layout"
      ]
    },
    "/_layout": {
      "filePath": "_layout.tsx",
      "children": [
        "/_layout/collection-1",
        "/_layout/collection-2",
        "/_layout/"
      ]
    },
    "/_layout/collection-1": {
      "filePath": "_layout/collection-1.tsx",
      "parent": "/_layout"
    },
    "/_layout/collection-2": {
      "filePath": "_layout/collection-2.tsx",
      "parent": "/_layout"
    },
    "/_layout/": {
      "filePath": "_layout/index.tsx",
      "parent": "/_layout"
    }
  }
}
ROUTE_MANIFEST_END */
