import { sortFilesByIndex } from '../../App.helpers';
import type { Collection, Picture } from '../../App.types';

const COLLECTION_ONE_PICTURES: Picture[] = [
  { aspectRatio: 2 / 3 },
  { aspectRatio: 2 / 3 },
  { aspectRatio: 2 / 3 },
  { aspectRatio: 2 / 3 },
  { aspectRatio: 2 / 3 },
  { aspectRatio: 2 / 3 },
  { aspectRatio: 4 / 5 },
  { aspectRatio: 2 / 3 },
  { aspectRatio: 2 / 3 },
  { aspectRatio: 2 / 3 },
  { aspectRatio: 2 / 3 },
  { aspectRatio: 2 / 3 },
  { aspectRatio: 2 / 3 },
  { aspectRatio: 2 / 3 },
  { aspectRatio: 2 / 3 },
  { aspectRatio: 2 / 3 },
  { aspectRatio: 2 / 3 },
  { aspectRatio: 4 / 5 },
  { aspectRatio: 2 / 3 },
  { aspectRatio: 2 / 3 },
  { aspectRatio: 2 / 3 },
  { aspectRatio: 2 / 3 },
  { aspectRatio: 2 / 3 },
  { aspectRatio: 2 / 3 },
  { aspectRatio: 2 / 3 },
  { aspectRatio: 2 / 3 },
  { aspectRatio: 4 / 5 },
  { aspectRatio: 2 / 3 },
  { aspectRatio: 2 / 3 },
  { aspectRatio: 2 / 3 },
  { aspectRatio: 2 / 3 },
  { aspectRatio: 2 / 3 },
  { aspectRatio: 2 / 3 },
  { aspectRatio: 2 / 3 },
  { aspectRatio: 4 / 5 },
  { aspectRatio: 2 / 3 },
  { aspectRatio: 2 / 3 },
  { aspectRatio: 2 / 3 },
  { aspectRatio: 2 / 3 },
  { aspectRatio: 2 / 3 },
  { aspectRatio: 2 / 3 },
  { aspectRatio: 2 / 3 },
  { aspectRatio: 4 / 5 },
  { aspectRatio: 2 / 3 },
  { aspectRatio: 2 / 3 },
  { aspectRatio: 2 / 3 },
  { aspectRatio: 2 / 3 },
  { aspectRatio: 2 / 3 },
  { aspectRatio: 2 / 3 },
  { aspectRatio: 4 / 5 },
  { aspectRatio: 2 / 3 },
  { aspectRatio: 2 / 3 },
  { aspectRatio: 2 / 3 },
  { aspectRatio: 2 / 3 },
  { aspectRatio: 2 / 3 },
  { aspectRatio: 2 / 3 },
  { aspectRatio: 4 / 5 },
  { aspectRatio: 4 / 5 },
  { aspectRatio: 2 / 3 },
  { aspectRatio: 2 / 3 },
  { aspectRatio: 2 / 3 },
  { aspectRatio: 2 / 3 },
  { aspectRatio: 2 / 3 },
  { aspectRatio: 4 / 5 },
  { aspectRatio: 2 / 3 },
  { aspectRatio: 2 / 3 },
  { aspectRatio: 2 / 3 },
  { aspectRatio: 2 / 3 },
  { aspectRatio: 2 / 3 },
  { aspectRatio: 2 / 3 },
  { aspectRatio: 4 / 5 },
  { aspectRatio: 2 / 3 },
  { aspectRatio: 2 / 3 },
  { aspectRatio: 2 / 3 },
  { aspectRatio: 2 / 3 },
  { aspectRatio: 2 / 3 },
  { aspectRatio: 2 / 3 },
  { aspectRatio: 2 / 3 },
  { aspectRatio: 2 / 3 },
  { aspectRatio: 2 / 3 },
  { aspectRatio: 4 / 5 },
  { aspectRatio: 2 / 3 },
  { aspectRatio: 2 / 3 },
  { aspectRatio: 2 / 3 },
  { aspectRatio: 2 / 3 },
  { aspectRatio: 2 / 3 },
  { aspectRatio: 4 / 5 },
  { aspectRatio: 2 / 3 },
  { aspectRatio: 2 / 3 },
  { aspectRatio: 2 / 3 },
  { aspectRatio: 2 / 3 },
  { aspectRatio: 2 / 3 },
  { aspectRatio: 2 / 3 },
  { aspectRatio: 2 / 3 },
  { aspectRatio: 2 / 3 },
  { aspectRatio: 2 / 3 },
  { aspectRatio: 2 / 3 },
  { aspectRatio: 4 / 5 },
  { aspectRatio: 2 / 3 },
  { aspectRatio: 2 / 3 },
  { aspectRatio: 2 / 3 },
  { aspectRatio: 2 / 3 },
  { aspectRatio: 2 / 3 },
  { aspectRatio: 2 / 3 },
  { aspectRatio: 4 / 5 },
  { aspectRatio: 2 / 3 },
  { aspectRatio: 2 / 3 },
  { aspectRatio: 2 / 3 },
  { aspectRatio: 2 / 3 },
  { aspectRatio: 2 / 3 },
  { aspectRatio: 2 / 3 },
  { aspectRatio: 2 / 3 },
  { aspectRatio: 2 / 3 },
  { aspectRatio: 4 / 5 },
  { aspectRatio: 2 / 3 },
  { aspectRatio: 2 / 3 },
  { aspectRatio: 2 / 3 },
  { aspectRatio: 2 / 3 },
  { aspectRatio: 2 / 3 },
  { aspectRatio: 2 / 3 },
  { aspectRatio: 2 / 3 },
  { aspectRatio: 2 / 3 },
  { aspectRatio: 2 / 3 },
].map((picture, index) => ({
  ...picture,
  path: sortFilesByIndex(
    Object.values(
      import.meta.glob('@assets/collection-1/pictures/*.{jpg,jpeg,JPEG}', {
        import: 'default',
        eager: true,
      }),
    ),
  )[index]!,
}));

export const COLLECTION_ONE: Collection = {
  index: 1,
  pathname: '/collection-1',
  title: 'paris',
  date: '2015 —',
  picturesCount: 123,
  thumbnails: {
    paths: sortFilesByIndex(
      Object.values(
        import.meta.glob('@assets/collection-1/thumbnails/*.{jpg,jpeg,JPEG}', {
          import: 'default',
          eager: true,
        }),
      ),
    ),
    opacity: 0.8,
  },
  pictures: COLLECTION_ONE_PICTURES,
};
