import { Collection } from '../../features/collection/collection.model';
import type { CollectionConfig } from '../../features/collection/collection.types';

const COLLECTION_ONE_PICTURES_CONFIG: CollectionConfig['picturesConfig'] = {
  paths: import.meta.glob('@assets/collection-1/pictures/*.{jpg,jpeg,JPEG}', {
    import: 'default',
    eager: true,
  }),
  data: [
    { aspectRatio: 2 / 3 },
    { aspectRatio: 2 / 3 },
    { aspectRatio: 2 / 3 },
    { aspectRatio: 2 / 3 },
    { aspectRatio: 2 / 3 },
    { aspectRatio: 2 / 3 },
    { aspectRatio: 4 / 5 },
    { aspectRatio: 2 / 3 },
    { aspectRatio: 2 / 3 },
    { aspectRatio: 2 / 3 },
    { aspectRatio: 2 / 3 },
    { aspectRatio: 2 / 3 },
    { aspectRatio: 2 / 3 },
    { aspectRatio: 2 / 3 },
    { aspectRatio: 2 / 3 },
    { aspectRatio: 2 / 3 },
    { aspectRatio: 2 / 3 },
    { aspectRatio: 4 / 5 },
    { aspectRatio: 2 / 3 },
    { aspectRatio: 2 / 3 },
    { aspectRatio: 2 / 3 },
    { aspectRatio: 2 / 3 },
    { aspectRatio: 2 / 3 },
    { aspectRatio: 2 / 3 },
    { aspectRatio: 2 / 3 },
    { aspectRatio: 2 / 3 },
    { aspectRatio: 4 / 5 },
    { aspectRatio: 2 / 3 },
    { aspectRatio: 2 / 3 },
    { aspectRatio: 2 / 3 },
    { aspectRatio: 2 / 3 },
    { aspectRatio: 2 / 3 },
    { aspectRatio: 2 / 3 },
    { aspectRatio: 2 / 3 },
    { aspectRatio: 4 / 5 },
    { aspectRatio: 2 / 3 },
    { aspectRatio: 2 / 3 },
    { aspectRatio: 2 / 3 },
    { aspectRatio: 2 / 3 },
    { aspectRatio: 2 / 3 },
    { aspectRatio: 2 / 3 },
    { aspectRatio: 2 / 3 },
    { aspectRatio: 4 / 5 },
    { aspectRatio: 2 / 3 },
    { aspectRatio: 2 / 3 },
    { aspectRatio: 2 / 3 },
    { aspectRatio: 2 / 3 },
    { aspectRatio: 2 / 3 },
    { aspectRatio: 2 / 3 },
    { aspectRatio: 4 / 5 },
    { aspectRatio: 2 / 3 },
    { aspectRatio: 2 / 3 },
    { aspectRatio: 2 / 3 },
    { aspectRatio: 2 / 3 },
    { aspectRatio: 2 / 3 },
    { aspectRatio: 2 / 3 },
    { aspectRatio: 4 / 5 },
    { aspectRatio: 4 / 5 },
    { aspectRatio: 2 / 3 },
    { aspectRatio: 2 / 3 },
    { aspectRatio: 2 / 3 },
    { aspectRatio: 2 / 3 },
    { aspectRatio: 2 / 3 },
    { aspectRatio: 4 / 5 },
    { aspectRatio: 2 / 3 },
    { aspectRatio: 2 / 3 },
    { aspectRatio: 2 / 3 },
    { aspectRatio: 2 / 3 },
    { aspectRatio: 2 / 3 },
    { aspectRatio: 2 / 3 },
    { aspectRatio: 4 / 5 },
    { aspectRatio: 2 / 3 },
    { aspectRatio: 2 / 3 },
    { aspectRatio: 2 / 3 },
    { aspectRatio: 2 / 3 },
    { aspectRatio: 2 / 3 },
    { aspectRatio: 2 / 3 },
    { aspectRatio: 2 / 3 },
    { aspectRatio: 2 / 3 },
    { aspectRatio: 2 / 3 },
    { aspectRatio: 4 / 5 },
    { aspectRatio: 2 / 3 },
    { aspectRatio: 2 / 3 },
    { aspectRatio: 2 / 3 },
    { aspectRatio: 2 / 3 },
    { aspectRatio: 2 / 3 },
    { aspectRatio: 4 / 5 },
    { aspectRatio: 2 / 3 },
    { aspectRatio: 2 / 3 },
    { aspectRatio: 2 / 3 },
    { aspectRatio: 2 / 3 },
    { aspectRatio: 2 / 3 },
    { aspectRatio: 2 / 3 },
    { aspectRatio: 2 / 3 },
    { aspectRatio: 2 / 3 },
    { aspectRatio: 2 / 3 },
    { aspectRatio: 2 / 3 },
    { aspectRatio: 4 / 5 },
    { aspectRatio: 2 / 3 },
    { aspectRatio: 2 / 3 },
    { aspectRatio: 2 / 3 },
    { aspectRatio: 2 / 3 },
    { aspectRatio: 2 / 3 },
    { aspectRatio: 2 / 3 },
    { aspectRatio: 4 / 5 },
    { aspectRatio: 2 / 3 },
    { aspectRatio: 2 / 3 },
    { aspectRatio: 2 / 3 },
    { aspectRatio: 2 / 3 },
    { aspectRatio: 2 / 3 },
    { aspectRatio: 2 / 3 },
    { aspectRatio: 2 / 3 },
    { aspectRatio: 2 / 3 },
    { aspectRatio: 4 / 5 },
    { aspectRatio: 2 / 3 },
    { aspectRatio: 2 / 3 },
    { aspectRatio: 2 / 3 },
    { aspectRatio: 2 / 3 },
    { aspectRatio: 2 / 3 },
    { aspectRatio: 2 / 3 },
    { aspectRatio: 2 / 3 },
    { aspectRatio: 2 / 3 },
    { aspectRatio: 2 / 3 },
  ],
};

const COLLECTION_ONE_CONFIG: CollectionConfig = {
  index: 1,
  pathname: '/collection-1',
  title: 'paris',
  date: '2015 —',
  thumbnailsConfig: {
    paths: import.meta.glob(
      '@assets/collection-1/thumbnails/*.{jpg,jpeg,JPEG}',
      {
        import: 'default',
        eager: true,
      },
    ),
    opacity: 0.8,
  },
  picturesConfig: COLLECTION_ONE_PICTURES_CONFIG,
};

export const collectionOne = new Collection(COLLECTION_ONE_CONFIG);
