import { sortFilesByIndex } from '../../App.helpers';
import type { Collection, Picture } from '../../App.types';

const COLLECTION_TWO_PICTURES: Picture[] = [
  { aspectRatio: 4 / 5 },
  { aspectRatio: 4 / 5 },
  { aspectRatio: 4 / 3 },
  { aspectRatio: 4 / 5 },
  { aspectRatio: 4 / 5 },
  { aspectRatio: 4 / 3 },
  { aspectRatio: 4 / 3 },
  { aspectRatio: 4 / 5 },
  { aspectRatio: 4 / 5 },
  { aspectRatio: 4 / 5 },
  { aspectRatio: 4 / 5 },
  { aspectRatio: 4 / 5 },
  { aspectRatio: 4 / 3 },
  { aspectRatio: 4 / 5 },
  { aspectRatio: 4 / 5 },
  { aspectRatio: 4 / 3 },
  { aspectRatio: 4 / 5 },
  { aspectRatio: 4 / 5 },
  { aspectRatio: 4 / 3 },
  { aspectRatio: 4 / 3 },
  { aspectRatio: 4 / 5 },
  { aspectRatio: 4 / 5 },
  { aspectRatio: 4 / 5 },
  { aspectRatio: 4 / 3 },
  { aspectRatio: 4 / 5 },
  { aspectRatio: 4 / 5 },
  { aspectRatio: 4 / 5 },
  { aspectRatio: 4 / 5 },
  { aspectRatio: 4 / 3 },
  { aspectRatio: 4 / 3 },
  { aspectRatio: 4 / 3 },
  { aspectRatio: 4 / 5 },
  { aspectRatio: 4 / 5 },
  { aspectRatio: 4 / 5 },
  { aspectRatio: 4 / 3 },
  { aspectRatio: 4 / 3 },
  { aspectRatio: 4 / 3 },
  { aspectRatio: 4 / 5 },
  { aspectRatio: 4 / 5 },
  { aspectRatio: 4 / 5 },
  { aspectRatio: 4 / 5 },
  { aspectRatio: 4 / 3 },
  { aspectRatio: 4 / 3 },
  { aspectRatio: 4 / 3 },
  { aspectRatio: 4 / 5 },
  { aspectRatio: 4 / 5 },
  { aspectRatio: 4 / 3 },
  { aspectRatio: 4 / 5 },
  { aspectRatio: 4 / 5 },
  { aspectRatio: 4 / 5 },
  { aspectRatio: 4 / 3 },
  { aspectRatio: 4 / 3 },
  { aspectRatio: 4 / 5 },
  { aspectRatio: 4 / 5 },
  { aspectRatio: 4 / 3 },
  { aspectRatio: 4 / 5 },
  { aspectRatio: 4 / 5 },
  { aspectRatio: 4 / 3 },
  { aspectRatio: 4 / 5 },
  { aspectRatio: 4 / 3 },
  { aspectRatio: 4 / 5 },
  { aspectRatio: 4 / 5 },
  { aspectRatio: 4 / 5 },
  { aspectRatio: 4 / 5 },
  { aspectRatio: 4 / 3 },
  { aspectRatio: 4 / 3 },
  { aspectRatio: 4 / 3 },
  { aspectRatio: 4 / 5 },
  { aspectRatio: 4 / 3 },
  { aspectRatio: 4 / 5 },
  { aspectRatio: 4 / 5 },
  { aspectRatio: 3 / 2 },
  { aspectRatio: 3 / 2 },
  { aspectRatio: 3 / 2 },
  { aspectRatio: 3 / 2 },
  { aspectRatio: 3 / 2 },
  { aspectRatio: 3 / 2 },
  { aspectRatio: 3 / 2 },
  { aspectRatio: 3 / 2 },
  { aspectRatio: 3 / 2 },
  { aspectRatio: 3 / 2 },
  { aspectRatio: 3 / 2 },
  { aspectRatio: 3 / 2 },
  { aspectRatio: 3 / 2 },
  { aspectRatio: 3 / 2 },
  { aspectRatio: 3 / 2 },
  { aspectRatio: 3 / 2 },
  { aspectRatio: 4 / 5 },
  { aspectRatio: 4 / 3 },
  { aspectRatio: 4 / 3 },
  { aspectRatio: 4 / 5 },
  { aspectRatio: 4 / 5 },
  { aspectRatio: 4 / 5 },
  { aspectRatio: 4 / 3 },
  { aspectRatio: 4 / 5 },
  { aspectRatio: 4 / 5 },
  { aspectRatio: 4 / 5 },
  { aspectRatio: 4 / 3 },
  { aspectRatio: 4 / 5 },
  { aspectRatio: 4 / 5 },
  { aspectRatio: 4 / 5 },
  { aspectRatio: 4 / 3 },
  { aspectRatio: 4 / 3 },
  { aspectRatio: 4 / 3 },
  { aspectRatio: 4 / 5 },
  { aspectRatio: 4 / 5 },
].map((picture, index) => ({
  ...picture,
  path: sortFilesByIndex(
    Object.values(
      import.meta.glob('@assets/collection-2/pictures/*.{jpg,jpeg,JPEG}', {
        import: 'default',
        eager: true,
      }),
    ),
  )[index]!,
}));

export const COLLECTION_TWO: Collection = {
  index: 2,
  pathname: '/collection-2',
  title: 'sud',
  date: '2014 —',
  picturesCount: 106,
  thumbnails: {
    paths: sortFilesByIndex(
      Object.values(
        import.meta.glob('@assets/collection-2/thumbnails/*.{jpg,jpeg,JPEG}', {
          import: 'default',
          eager: true,
        }),
      ),
    ),
    opacity: 0.8,
  },
  pictures: COLLECTION_TWO_PICTURES,
};
