import { Collection } from '../../features/collection/collection.model';
import type { CollectionConfig } from '../../features/collection/collection.types';

const COLLECTION_TWO_PICTURES_CONFIG: CollectionConfig['picturesConfig'] = {
  paths: import.meta.glob('@assets/collection-2/pictures/*.{jpg,jpeg,JPEG}', {
    import: 'default',
    eager: true,
  }),
  data: [
    { aspectRatio: 4 / 5 },
    { aspectRatio: 4 / 5 },
    { aspectRatio: 4 / 3 },
    { aspectRatio: 4 / 5 },
    { aspectRatio: 4 / 5 },
    { aspectRatio: 4 / 3 },
    { aspectRatio: 4 / 3 },
    { aspectRatio: 4 / 5 },
    { aspectRatio: 4 / 5 },
    { aspectRatio: 4 / 5 },
    { aspectRatio: 4 / 5 },
    { aspectRatio: 4 / 5 },
    { aspectRatio: 4 / 3 },
    { aspectRatio: 4 / 5 },
    { aspectRatio: 4 / 5 },
    { aspectRatio: 4 / 3 },
    { aspectRatio: 4 / 5 },
    { aspectRatio: 4 / 5 },
    { aspectRatio: 4 / 3 },
    { aspectRatio: 4 / 3 },
    { aspectRatio: 4 / 5 },
    { aspectRatio: 4 / 5 },
    { aspectRatio: 4 / 5 },
    { aspectRatio: 4 / 3 },
    { aspectRatio: 4 / 5 },
    { aspectRatio: 4 / 5 },
    { aspectRatio: 4 / 5 },
    { aspectRatio: 4 / 5 },
    { aspectRatio: 4 / 3 },
    { aspectRatio: 4 / 3 },
    { aspectRatio: 4 / 3 },
    { aspectRatio: 4 / 5 },
    { aspectRatio: 4 / 5 },
    { aspectRatio: 4 / 5 },
    { aspectRatio: 4 / 3 },
    { aspectRatio: 4 / 3 },
    { aspectRatio: 4 / 3 },
    { aspectRatio: 4 / 5 },
    { aspectRatio: 4 / 5 },
    { aspectRatio: 4 / 5 },
    { aspectRatio: 4 / 5 },
    { aspectRatio: 4 / 3 },
    { aspectRatio: 4 / 3 },
    { aspectRatio: 4 / 3 },
    { aspectRatio: 4 / 5 },
    { aspectRatio: 4 / 5 },
    { aspectRatio: 4 / 3 },
    { aspectRatio: 4 / 5 },
    { aspectRatio: 4 / 5 },
    { aspectRatio: 4 / 5 },
    { aspectRatio: 4 / 3 },
    { aspectRatio: 4 / 3 },
    { aspectRatio: 4 / 5 },
    { aspectRatio: 4 / 5 },
    { aspectRatio: 4 / 3 },
    { aspectRatio: 4 / 5 },
    { aspectRatio: 4 / 5 },
    { aspectRatio: 4 / 3 },
    { aspectRatio: 4 / 5 },
    { aspectRatio: 4 / 3 },
    { aspectRatio: 4 / 5 },
    { aspectRatio: 4 / 5 },
    { aspectRatio: 4 / 5 },
    { aspectRatio: 4 / 5 },
    { aspectRatio: 4 / 3 },
    { aspectRatio: 4 / 3 },
    { aspectRatio: 4 / 3 },
    { aspectRatio: 4 / 5 },
    { aspectRatio: 4 / 3 },
    { aspectRatio: 4 / 5 },
    { aspectRatio: 4 / 5 },
    { aspectRatio: 3 / 2 },
    { aspectRatio: 3 / 2 },
    { aspectRatio: 3 / 2 },
    { aspectRatio: 3 / 2 },
    { aspectRatio: 3 / 2 },
    { aspectRatio: 3 / 2 },
    { aspectRatio: 3 / 2 },
    { aspectRatio: 3 / 2 },
    { aspectRatio: 3 / 2 },
    { aspectRatio: 3 / 2 },
    { aspectRatio: 3 / 2 },
    { aspectRatio: 3 / 2 },
    { aspectRatio: 3 / 2 },
    { aspectRatio: 3 / 2 },
    { aspectRatio: 3 / 2 },
    { aspectRatio: 3 / 2 },
    { aspectRatio: 4 / 5 },
    { aspectRatio: 4 / 3 },
    { aspectRatio: 4 / 3 },
    { aspectRatio: 4 / 5 },
    { aspectRatio: 4 / 5 },
    { aspectRatio: 4 / 5 },
    { aspectRatio: 4 / 3 },
    { aspectRatio: 4 / 5 },
    { aspectRatio: 4 / 5 },
    { aspectRatio: 4 / 5 },
    { aspectRatio: 4 / 3 },
    { aspectRatio: 4 / 5 },
    { aspectRatio: 4 / 5 },
    { aspectRatio: 4 / 5 },
    { aspectRatio: 4 / 3 },
    { aspectRatio: 4 / 3 },
    { aspectRatio: 4 / 3 },
    { aspectRatio: 4 / 5 },
    { aspectRatio: 4 / 5 },
  ],
};

const COLLECTION_TWO_CONFIG: CollectionConfig = {
  index: 2,
  pathname: '/collection-2',
  title: 'sud',
  date: '2014 —',
  thumbnailsConfig: {
    paths: import.meta.glob(
      '@assets/collection-2/thumbnails/*.{jpg,jpeg,JPEG}',
      {
        import: 'default',
        eager: true,
      },
    ),
    opacity: 0.8,
  },
  picturesConfig: COLLECTION_TWO_PICTURES_CONFIG,
};

export const collectionTwo = new Collection(COLLECTION_TWO_CONFIG);
